algolia/algoliasearch-client-go

algoliasearch/Transport.go
This PR fixes a bug that caused me a panic when calling `client.SetExtraHeader`.
I'm implementing a CLI search that uses a token generated via  a `createCollectionScopedKey` call. I still can't get the faceting to work, but this fix at least helps my panic. I
```
panic: runtime error: assignment to entry in nil map
goroutine 16 [running]:
runtime.panic(0x2edde0, 0x4db7f3)
/usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
github.com/algolia/algoliasearch-client-go/algoliasearch.(*Client).SetExtraHeader(0xc2080381b0, 0x363630, 0x19, 0xc20801aaf0, 0x41)
/Users/csquared/projects/go/src/github.com/algolia/algoliasearch-client-go/algoliasearch/Client.go:29 +0x8d
main.(*CLI).Search(0xc208074b60, 0xc208000e88, 0x4)
/Users/csquared/projects/go/src/github.com/usecanvas/canvas/search.go:24 +0x33a …
```
=> initialize headers map in Transport

algoliasearch/Transport.go
The transport is a shared resource that can be used from many threads. It doesn't make a lot of sense to be changing its values underneath inflight requests. If different timeout values are needed the client should hold onto multiple transports.
The client of http.Do is responsible for closing the resp body regardless of the http status.
=> simplify transport. should close response bodies.

README.md
Minor README change to add missing method names for batch operations.
=> Add method names to batch section.

algoliasearch/Transport.go
The Response's Body wasn't read to completion before being closed. It led to
multiple retries from the default HTTP client. This commit fixes this issue by
actually reading the Body to completion.
=> Read Response's Body to completion before closing it

algoliasearch/Client.go, algoliasearch/Client_test.go, algoliasearch/Transport.go
- Centralized code for creating a new http client.
- Removed reflect calls in favor of simpler plain type switches.
- Go fmt'd code in /algoliasearch.
=> Transport: refactor for httpClient creator + remove reflect

algoliasearch/algoliasearch.go, algoliasearch/client.go, algoliasearch/client_test.go, algoliasearch/index.go
=> Rename API key-related methods to be more consistent with the other API clients

algoliasearch/types_batch.go
=> Do not encode the `objectID` when passed in batch's body

algoliasearch/algoliasearch.go, algoliasearch/client.go, algoliasearch/client_test.go, algoliasearch/secured_api_key.go
From here https://github.com/algolia/algoliasearch-client-go/issues/59
=> Make GenerateSecuredAPIKey not part of Client

algoliasearch/client.go, algoliasearch/types_index.go
This bug fix exports the `Items` field in the `listIndexesRes` struct. This makes it so calls to `ListIndexes()` will be able to get back the Algolia indexes since a field needs to be exported to be unmarshalled from JSON.
=> Export listIndexesRes.Items so the JSON response can unmarshal into it

algoliasearch/algoliasearch.go, algoliasearch/client.go, algoliasearch/transport.go
This added functionality enables the use of alternate transport mechanisms, such as those required for use within Google App Engine [1]. My company has had a branch for a while maintaining this change: https://github.com/rastech/algoliasearch-client-go/commit/59d17d0313aae8d66ed345b4737ee507d358d21e which brings in the appengine libraries as a dependency and is thus probably undesirable for the main repo. Without that [handling](https://github.com/rastech/algoliasearch-client-go/commit/59d17d0313aae8d66ed345b4737ee507d358d21e#diff-606c6ee02e002516ad4f7614a535f7e8R93) for the `*urlfetch.Transport` type, the timeouts won't be properly set, but I put a note in the method comments to that effect.
This also corrects a few minor things from golint.
[1] …
=> Allow for a custom HTTP client to be set

algoliasearch/testing.go
=> Replace `syscall.GetEnv` call from the tests with `os.GetEnv` for GAE use

algoliasearch/types_index.go
The following fields were missing from the IndexRes struct and have been added:
- FileSize (integer)
- NumberOfPendingTask (integer)
From #105
=> Add two missing fields to IndexRes struct

algoliasearch/algoliasearch.go, algoliasearch/index.go
This PR adds a variation of `GetObjects` that takes in an `attrs` parameter to allow users to retrieve only the selected attributes of multiple objects.
=> Add GetObjectsAttrs method to get selected attributes of multiple objects

algoliasearch/transport.go
transport.go#L171 tries to make a request to each host, until one
succeed and ignore errors unless there is no host left. But
transport.go#L249 can return with an error before closing
the response at L251. This error is not caught by Transport.request()
method unless there no other host to try.
Consequence of transport.go#L249 is that with a lot number of calls we
can arrive at a situation with a lot of socket remained open.
This commit fix the problem by defering the connection closure and move
the statement before any error can happen so that in any situation the
socket is closed.
CAT: #fix
REF: algolia/algoliasearch-client-go#287
=> Fix unlimited socket opening problem

algoliasearch/index.go
This PR fixes a bug retrieving attributes in the `index`'s `GetObjectsAttrs` and `GetObject` methods. In `GetObjectsAttrs`, the requested list of attributes is URL-escaped, while in `GetObject`, the attribute query params being passed into `encodeParams` are a `[]byte`, rather than a `string`. The result, in both cases, is that no attributes except the object ID are retrieved.
=> Fix query format in GetObject and GetObjectsAttrs

algoliasearch/index.go
As discussed here: https://github.com/algolia/algoliasearch-client-ruby/pull/211 this the same implementation for go.
Update: I've added wait for DeleteObjects to match [documentation](https://www.algolia.com/doc/api-client/go/indexing/#delete-by-query), but I think it should be like other functions and like documentation said: "All write operations in Algolia are asynchronous by design".
```go
func (i *index) DeleteByQuery(query string, params Map) (res BatchRes, err error) {
copy := duplicateMap(params)
copy["attributesToRetrieve"] = []string{"objectID"}
copy["hitsPerPage"] = 1000
copy["query"] = query
copy["distinct"] = 0
var browseRes BrowseRes
var objectIDs []string
var cursor string
for {
// Start browsing the content by cursor
if browseRes, err = i.Browse(copy, cursor); err != nil …
```
=> Improve DeleteByQuery performance

algoliasearch/types_settings.go
The setting is already returned in the settings API, but was never exposed in the settings type.
=> Add missing removeWordsIfNoResults to settings type

algoliasearch/check_query.go, algoliasearch/client_test.go, algoliasearch/index_test.go, algoliasearch/types_query.go
* Added `clickAnalytics` boolean parameter to acceptable search options
* Added `queryID` to search response
When we implement Click Analytics feature, we need to add `clickAnalytics: true` to search option.
https://www.algolia.com/doc/tutorials/getting-started/how-to-implement-analytics/
And when we activate Click Analytics, the search response contains `queryID` parameter. We need to retrieve it from the response.
We can set `clickAnalytics` parameter and get `queryID` from the search response. It means we can use Click Analytics feature with golang SDK.
=> Add clickAnalytics to search option parameters

algoliasearch/check_query.go, algoliasearch/check_settings.go, algoliasearch/types_query.go, algoliasearch/types_settings.go
After investigation, we discovered that some query rules fields were
missing here and there. This commit now exposes the following fields:
- `enableRules` boolean as a query parameter
- `enableRules` boolean as a setting
- `appliedRules` slice of maps in the query response
- `indexUsed` string in the query response
- `userData` slice of maps in the query response
=> fix: Expose missing fields related to Query Rules

algoliasearch/algoliasearch.go, algoliasearch/client.go, algoliasearch/index.go
| Need Doc update   | yes (not sure)
The 2 methods about taskID initially available in the `Index` moved to the `Client`. The original methods on the index still work are **not** deprecated.
You could get some taskID from the engine without necessarily having an instance of Index. Instead of instantiating an index that you won't need, you can now call `QaitTask` and `GetStatus` on the client.
* It will be very useful for the new Analytics object (see https://github.com/algolia/algoliasearch-client-php/pull/408)
* We're planning to merge https://github.com/algolia/algoliasearch-client-php/pull/295 (and port it to all clients). Adding multipleObjects …
=> feat(client): Expose waitTask in the client

algoliasearch/transport.go
`runtime.Version()` returns something like "go1.10.1", I believe it's best to remove the first 2 characters.
=> Add golang version to UserAgent

algoliasearch/index_test.go, algoliasearch/types_settings.go
| New feature?      | no   
| Related Issue     | N/A
The following attributes were missing in the result Map returned by the
Settings.ToMap function:
* `enableRules`
* `ignorePlurals`
* `sortFacetValuesBy`
Also, some fields may not have been properly transformed because the
Settings.clean function was not called to clean some fields with sane
defaults.
This commits fixes all the aformentioned issues and adds a test to
ensure that any new field added to the Settings struct will make the
tests fail in not handled in the Settings.ToMap function.
=> fix: Export missing attributes in Settings.ToMap

release.sh
Adding a `release.sh` script to perform a release in a single step.
What it does is to:
1. Update the version of the client by changing it in the `algoliasearch/transport.go` file
2. Update the `ChangeLog.md` using our ChangeLog generator tool
3. Ask the user for confirmation of the changes to be commited
4. Commit, tag and push on the master branch
=> chore: Add release.sh script

Gopkg.lock, Gopkg.toml, algoliasearch/check_query.go, algoliasearch/check_rule.go, algoliasearch/index.go, algoliasearch/index_test.go, algoliasearch/types_query.go, algoliasearch/types_rule.go
All changes related to the release of Query Rules v2. For detailled informations, please take a look at the dedicated commit. Other commits simply add the associated tests and introduce a new dependency on github.com/mitchellh/mapstructure now used in tests only to ease response objects comparison.
New features available from the engine.
=> Query rules v2

algoliasearch/check_query.go, algoliasearch/check_query_test.go
Thanks to one customer report, we discovered that the documentation was
wrong regarding the way to set the `facetFilters` parameter. This commit
adds the support for other types (namely `[][]string` and
`[]interface{}`), so that all the following calls are now legit in Go:
```go
// category:Book
"facetFilters": "category:Book"
// category:Book AND author:J.K. Rowling
"facetFilters": []string{
"category:Book",
"author:J.K. Rowling",
}
// (category:Book OR category:Movie) AND (author:J.K. Rowling OR author:Stephen King)
"facetFilters": [][]string{
[]string{"category:Book", "category:Movie"},
[]string{"author:J.K. Rowling", "author:Stephen King"},
}
// (category:Book OR category:Movie) AND author:J.K. Rowling
"facetFilters": []interface{}{
[]string{"category:Book", "category:Movie"}, …
```
=> fix: Add missing types for `facetFilters`

algoliasearch/index.go, algoliasearch/index_test.go
`Index::delete_object` needs a non-empty objectID
If the object_id is empty, the entire index will be deleted instead of one record.
=> fix: objectID is required to deleteObject

algoliasearch/types_key.go
There is a typo in QueryParameters. I am not sure this is the right way to fix it, there might be side effects that I haven't considered.
Feel free to update or close, or let me know what to do.
=> fix(key): Add QueryParameters in Key struct to fix typo

algoliasearch/index.go
=> changed: Ensure that after a index.move, the internal name of the index is correctly updated as well

algoliasearch/algoliasearch.go, algoliasearch/index.go, algoliasearch/index_test.go
| Related Issue     | N/A
changed: Deprecate Index.Move method in favor of Index.MoveTo
N/A
=> changed: Deprecate Index.Move method in favor of Index.MoveTo

algoliasearch/account_client.go, algoliasearch/account_client_test.go, algoliasearch/algoliasearch.go, algoliasearch/check_rule.go, algoliasearch/client.go, algoliasearch/errors.go, algoliasearch/index.go, algoliasearch/index_test.go, algoliasearch/secured_api_key_test.go, algoliasearch/testing_test.go
* added: Implement AccountClient.CopyIndex 
* changed: remove extra empty line 
* changed: Use the environment variables from our Common Test Suite for testing 
* added: Implement Index.GetAppID and Client.GetAppID methods 
* added: Implement Index.Replace{Objects,Rules,Synonyms} 
* deprecated: Index.{Delete,Clear} replaced by Client.{Delete,Clear}Index 
* added: Implement Client.Copy{Settings,Synonyms,Rules} 
* deprecated: Index.{Copy,Move} replaced by Client.{Copy,Move}Index
=> Offsite changes

algoliasearch/client.go, algoliasearch/index.go
This commit ensures that we avoid targeting DSNs when adding API keys.
| Related Issue     | Fix #...  
=> fix: change AddAPIKey type from read to write

algoliasearch/types_abtesting.go
Expose the new `customSearchParameters` fields to AB test variant in order to submit AA tests. This PR doesn't include the test because the CTS is currently only implemented in the v3 branch of the client and this is where the test now lives. At the moment, adding a test for AA testing would conflict with the existing AB testing test, so I choose not to do the job twice in the two branches.
=> Aa testing custom search parameters

algoliasearch/index.go
| Related Issue     | Fix #456 
Do not URL encode objectIDs passed via the body of `GetObjects` requests.
Otherwise, objects contained expendable characters cannot be retrieved.
=> fixed: Correctly retrieve objectIDs using GetObjects

algolia/search/responses_search.go
| BC breaks?        | yes    
AutomaticRadius is a float: https://www.algolia.com/doc/api-reference/api-methods/search/?language=javascript#method-response-automaticradius
^ see above
=> fix(response): AutomaticRadius is a float not a string

algolia/search/responses_search.go
| BC breaks?        | yes     
`abTestVariantID` is a int not a string, see: https://www.algolia.com/doc/api-reference/api-methods/search/?language=javascript#method-response-abtestvariantid
error while unmarshalling the result of a query
=> fix(response): ABTestVariantID is an int not a string

algolia/errs/algolia_err.go, algolia/errs/algolia_err_test.go, algolia/transport/transport.go
| BC breaks?        | yes     
In go errors are interfaces, so they can be also pointers. So we need to for values and pointer in the type cast.
See: https://play.golang.org/p/VUR8qafldKk
Thanks to @marchelbling for spotting the need of the double check
=> fix: algolia_err, use pointers

algolia/analytics/utils.go
| Related Issue     | n/a
All our regional APIs use the following structure: `$feature.$region.algolia.$tld`. For analytics, the `$region` was misplaced. 
Incorrect analytics domain meaning that reigonalized Analytics / A/B Tests calls would previously fail.
=> fix: update analytics regional host name template

algolia/search/index.go, cts/index/exists_test.go
| Related Issue     | Fix #512  
This adds the `Index.Exists` method in the client. It follows the [spec](https://github.com/algolia/algoliasearch-client-specs/blob/master/features/index-exists.md) and [common test suite](https://github.com/algolia/algoliasearch-client-specs/tree/master/common-test-suite#Exists).
=> feat(index): add exists method

algolia/search/synonym.go, algolia/search/synonym_alt_correction_1.go, algolia/search/synonym_alt_correction_2.go, algolia/search/synonym_one_way.go, algolia/search/synonym_test.go
fixed(synonym): correctly deserialize synonyms set via the Algolia dashboard
Synonyms saved via the Algolia dashboard see their type field
lowercased, which means that we at deserialization time, we cannot only
expect camel casing for synonym types. The impacted synonym types were:
- `oneWaySynonym` with `onewaysynonym`
- `altCorrection1` with `altcorrection1`
- `altCorrection2` with `altcorrection2`
This commit ensures we correctly deserialize those synonyms, even if
their type field is lowercased.
Close #514
=> Fix lowercase synonym type

algolia/search/responses_search.go
=> fixed: use correct type (string) for QueryRes.AutomaticRadius field

algolia/debug/debug.go, algolia/debug/utils.go, algolia/transport/transport.go, algolia/transport/transport_test.go
While enabling GZIP encoding for POST/PUT requests in previous commits,
we discovered that every JSON request body was serialized in memory
using `json.Marshal` instead of going through a `json.Encoder`, hence
avoiding to load the full content in memory.
This commit is fixing this issue by using an intermediate `json.Encoder`
to prevent in-memory loading of the content. This approach is still
compatible with the GZIP feature which was recently implemented as the
`json.Encoder` is simply the input of the `gzip.Writer` in that case.
This ensure everything is still buffered.
=> Improve performances of body encoding

algolia/errs/errors.go, algolia/search/index_objects.go, algolia/search/responses_search.go, cts/index/search_test.go
=> Implement unit testing relevance helper functions

algolia/search/index_interface.go
Because the Exists() method was missing, the Index could not be mocked
as expected.
=> fix(index): add missing Exists() method to the IndexInterface (#537)

algolia/errs/errors.go, algolia/search/client_interface.go, algolia/search/client_keys.go, cts/search/secured_api_keys_test.go
| Related Issue     | Fix #536
The remaining validity duration of a secured API generated with the
`opt.ValidUntil()` parameter can now be checked thanks to the new
`GetSecuredAPIKeyRemainingValidity()` method of the `search.Client`.
=> feat(key): add Client.GetSecuredAPIKeyRemainingValidity() (#536)

algolia/search/client_interface.go, algolia/search/client_mcm.go, cts/search/mcm_test.go
| Related Issue     | Fix #545
Multiple MCM user IDs can now be assigned in a single call by using
`Client.AssignUserIDs()` method.
=> feat(mcm): add Client.AssignUserIDs() method (#545)

algolia/internal/gen/options.go, algolia/internal/opt/cluster.go, algolia/internal/opt/cluster_test.go, algolia/opt/cluster.go, algolia/opt/option_getters_test.go, algolia/search/mcm.go
**Summary**
Fix #551 
The `Client.SearchUserIDs()` method was wrongly accepting
opt.ClusterName optional parameter to filter userIDs search queries
based on the cluster. However, this is rejected by the engine, which
only recognizes and accepts `cluster` payloads. To reflect this, the
`opt.ClusterName` option was renamed into `opt.Cluster` instead.
=> fix(mcm): replace invalid otp.ClusterName with opt.Cluster for SearchUserIDs()

algolia/errs/errors.go, algolia/search/client_keys.go, cts/search/secured_api_keys_test.go, cts/testing_utils.go
**Summary**
The `errs.ErrValidUntilInvalid` error was introduced to signify that the
`validUntil` string parameter of a secured API key could not be parsed
as an integer by the `Client.GetSecuredAPIKeyRemainingValidity()`
method. However, since this string value is always extracted thanks to a
regexp looking for a integer of maximum length 10, the conversion can
never fail, making this error case useless.
This commit hence removes this useless error which get never returned.
=> Invalid validuntil for get secured api key remaining validity

algolia/search/index_objects.go
The i.path accepts a string format instead of a string.
When the objectID contains characters such as %, the request URL will be built incorrectly.
=> Fix incorrect Index path arguments

.travis.yml
Bump golangci-lint.
Drop os since it's already the default.
Cleaner travis script and keeping up to date.
=> chore(travis): bump golangci and remove os since default

algolia/transport/requester.go
transport.DefaultHTTPClient exposes the default *http.Client used by the
different Client instances of the Algolia API client.
Most users should not need to access this http.Client.
This helper is only useful for users who wish to keep the default behavior
of the Algolia API client (by wrapping it in a user-defined instance of
transport.Requester) but would like to wrap it into a middleware layer or pass
it to an HTTP interceptor.
=> feat(transport): expose the default HTTP client via transport.DefaultHTTClient()

algolia/search/rule_condition.go, algolia/search/rule_condition_test.go
Since the introduction of Contextual Query Rules in `f2cdcdd`, the
anchoring and pattern parts were omitted when serialized if one of them
was missing. However, the correct behavior is to serialized both fields
when at least of them is present. This commit fixes this.
Close #572
=> fix(rule): correctly serialize RuleCondition

algolia/search/index.go, cts/index/url_encoding_index_name_test.go, cts/testing_utils.go
We've recently identified that the user-provided index name, when passed
to the URL internally, was not URL-encoded as one would expect. This
could result in the user targetting wrong indices, either when using the Go
client, or other API clients, including frontend integrations.
After multiple internal discussions, we finally decided to introduce
this change, even though it may be breaking for some users, in a minor
version. We consider that the future benefits of fixing this issue for
future new users holds more positive impact than the negative one of
having existing users to have to manually ensure their index names are
correct.
Close #574
=> fix(search): correctly encode index name in URIs (#574)

algolia/analytics/utils.go, algolia/region/region.go
The `region.EU` was never accepted by the Analytics API. This commit
introduces the right region `region.DE` and uses it as part of the valid
configurable regions for the Analytics client.
=> fix(analytics): accept region.DE instead of region.EU for Analytics configuration

algolia/recommendation/client.go
chore(travis): add go 1.14
Adding Go 1.14 to the travis.
Adding AppId to the recommendation constructor
=> fix(recommendation): add app id to the default config

algolia/analytics/client.go, algolia/analytics/responses_ab_testing.go, algolia/search/client_multiple.go, algolia/search/index.go, algolia/search/index_interface.go, algolia/search/responses_indexing.go, algolia/search/responses_multiple.go, algolia/search/responses_personalization.go, algolia/search/responses_tasks.go, algolia/search/utils.go
We've recently noticed that all integers representing task IDs coming
from Algolia were wrongly typed as 32b integers. However, the Algolia
engine is returning JSON numbers which can go beyond the range of 32b: a
JSON number can be as big as 2^53.
For this reason, this commit is changing the type of all the taskID
variables as well as all function accepting task IDs from `int` to `int64`.
This change was automated, for the most part, with the two following sed
commands:
```
find . -name '*.go' -exec gsed -Ei 's/taskID( +)int\)/taskID\1int64\)/' {} \;
find . -name '*.go' -exec gsed -Ei 's/TaskID( +)int/TaskID\1int64/' {} \;
```
Fix #591
=> fix: use int64 instead of int (32b integers) to represent task IDs everywhere

.circleci/config.yml, .golangci.yml, README.md, algolia/transport/transport.go
Because we were not checking if the error returning by the underlying
requester, we could not determine if the HTTP call failed because of
user-defined context being cancelled because of a timeout being reached or
an exceeding deadline.
This commit introduce an early return for those cases. This way, we do
not perform multiple retries against other hosts when the user-defined
context is already done, because of a context timeout or a context deadline.
Note that we did not use the error wrapping mechanism from Go 1.13 with
`errors.Is()` and `errors.As()` since we are still supporting Go down to
Go 1.11 for now.
Close #596
=> refactor(transport): ensure early termination upon context cancellation

algolia/transport/requester.go
After the report from @asurak about a potential memory leak within the
Go API client, we've been able to reproduce the issue by starting new
`search.Client` instances in the same program from many goroutines (~50 or
higher) and performing simple search queries to the engine over the
network. Under these conditions, the program was seeing its system memory
increased linearly, without any memory being released to the OS by the
GC. When performing the search queries with hardcoded requests using the Go
standard library's `http.DefaultClient`, the issue disappeared.
After profiling the memory usage (using `pprof`), we've noticed that our top
memory usage was due to many invocations of `bytes.MakeSlice` made by
the `*http.Client.Transport` instance that we create for each new
instance of the …
=> fix(transport): prevent memory leak when many clients are instantiated by multiple goroutines

algolia/analytics/responses_ab_testing.go
| Related Issue     | Fix https://github.com/algolia/algoliasearch-client-specs-internal/pull/142
| Need Doc update   | no (already done)
Add the field `trackedSearchCount` to AB testing metrics returned.
=> feat(analytics): add tracked search count

algolia/analytics/responses_ab_testing.go
| New feature?      | no 
| Related Issue     | https://algolia.slack.com/archives/C336MP4UA/p1601275875007500
```
cannot deserialize response's body: json: cannot unmarshal number 15.814493551189196 into Go struct field VariantResponse.variants.averageClickPosition of type int
```
=> fix(analytics): correct AB testing average click pos type

algolia/insights/types.go
| BC breaks?        | no    
| Related Issue     | Fix #639 
This PR fixes incorrect Insights event timestamp conversion to milliseconds and JSON serialization
=> fix: Insights event timestamp serialization

algolia/search/client_multiple.go, algolia/search/index.go, algolia/search/index_interface.go, algolia/search/responses_indexing.go, algolia/search/responses_multiple.go, algolia/search/responses_tasks.go, algolia/search/utils.go, algolia/wait/waitable.go, cts/extra/intermediate_errors_test.go
Add the ability to provide request options on wait task calls .
It's not possible to pass `opt.ExposeIntermediateNetworkErrors(true)` to **WaitTask** so in case of network failure, it's impossible to debug it.
=> feat(search): add request options on wait functions

algolia/transport/transport.go, algolia/transport/transport_test.go
Improve error message on unmarshalTo errors
When the client is unable to deserialize a response, there's currently no way to know the original message and what it contains. This PR will improve it.
=> feat(Transport): improve error message on unmarshalTo errors

algolia/search/responses_list_indexes.go, algolia/search/responses_list_indexes_test.go
Add 2 fields in the ListIndexes response as described in the [documentation](https://www.algolia.com/doc/api-reference/api-methods/list-indices/)
Unavailable field in the client
=> feat(ListIndexes): add primary/replicas fields

algolia/transport/transport.go, algolia/transport/transport_test.go
| BC breaks?        | no   
| Related Issue     | Fix #648
In case of non-retryable transport error with nil body, the error is returned directly skipping the attempt to parse the body. 
A few HS tickets ([1](https://secure.helpscout.net/conversation/1436477033/335677/), [2](https://secure.helpscout.net/conversation/1434758878/335102?folderId=2966557)) reported the panic happened due to attempt to unmarshal the nil body in case of non-retryable error.
=> fix: panic in case of non-retryable error with nil body

algolia/search/requests_search.go, algolia/search/requests_search_test.go
| New feature?      | no   
| Related Issue     | Fix #654 
Current implementation of `SearchForFacetValues` method ignores `opt.Query` parameter from the variadic parameters list due to `opt.Query` not being a part of `QueryParams` structure.
This PR adds the `opt.Query` parameter to the `searchForFacetValuesParams` structure and fixes this issue.
=> fix: query parameter support in Search for facet values parameters list

cts/search/dictionaries/compounds_test.go, cts/search/dictionaries/plurals_test.go, cts/search/dictionaries/stopwords_test.go
This PR makes the custom dictionaries skip to unblock the CI
CI doesn't fail anymore due to always-failing custom dictionaries integration tests
=> chore: Disable Custom Dictionaries integration tests

algolia/search/index.go, algolia/search/index_interface.go, algolia/search/index_test.go
| Related Issue     | Fix #663 
| Need Doc update   |no
Made it possible to get index name from `Index` interface.
this library's user can get index name and use it for logging and so on.
=> feat(index): Make it possible to get index name

algolia/internal/gen/templates/settings.go.tmpl, algolia/search/rendering_content.go, algolia/search/rendering_content_test.go, algolia/search/settings.go
- Add the `RenderingContent` as a Settings field.
- Add a convenient `FacetValuesOrder` constructor
=> feat(RenderingContent): Add the rendering content as a settings field

algolia/personalization/client.go, algolia/personalization/client_personalization.go, algolia/personalization/configuration.go, algolia/personalization/responses_personalization.go, algolia/personalization/types_personalization.go, algolia/personalization/utils.go, algolia/recommendation/client.go, cts/recommendation/personalization_strategy_test.go, cts/testing_utils.go
| Related Issue     | Fix #665 
This PR renames the recommendation package to personalization, keeping the recommendation package deprecated.
Fix #665
=> chore: Rename recommendation package to personalization package

algolia/search/index.go, cts/index/exists_test.go
| Related Issue     | Fix #672  
Fix index.Exists() to return error if the error is not not-found error.
#672
=> fix: Make Index.Exists() return error if the error is not not-found error

algolia/suggestions/bool_or_string_array.go, algolia/suggestions/client_config.go, algolia/suggestions/client_config_test.go, cts/suggestions/config_test.go
| New feature?      | yes/no    
| Related Issue     | Fix #671 
This PR introduces `BoolOrStringArray` type to properly represent the query suggestions configuration `languages` value.
Described in #671
=> fix: Suggestion config bool value support

.circleci/config.yml
| New feature?      | no  
| Related Issue     | no
This PR uses a matrix for the different go version we want to build. It avoids copy/paste the entire job for each version. The idea behind this change is to eventually split the unit from the integration tests. We will be able to run the unit tests on forked PRs. We have change the required checks from `test-1-XX` to `test-1.XX`.
N/A
=> chore(circleci): use matrix

algolia/search/rule_condition.go, algolia/search/rule_condition_test.go
| Related Issue     | Fix #...  
The engine doesn't accept Query Rule condition pattern in case of missing `anchoring` parameter. 
This PR suppress `pattern` parameter marshalling if the anchoring parameter is empty.
=> fix: Suppress rule condition pattern marshalling in case of empty anchoring

.circleci/config.yml
| New feature?      | no   
| Related Issue     | -
This PR split the unit tests and the integration tests in CircleCI into dedicated jobs: `unit-tests` & `integration-tests`.
The `integrations-tests` require credentials, and those credentials are **NOT** forwarded to fork pull requests. It means that **ALL** pull requests made by any external contributor is failing from the CI point of view. The idea is to disable the integrations tests suite on fork pull request because anyway they won't pass (see [CircleCI documentation](https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/)).
We have to change the required checks from `test-1.XX` …
=> chore(circleci): split unit/integration tests

algolia/search/responses_search.go
`abTestID` is not currently returned from the client, even though it's a [documented value](https://www.algolia.com/doc/api-reference/api-methods/search/#method-response-abtestid)
This was handled in some of the other clients in the past. e.g. [javascript](https://github.com/algolia/algoliasearch-client-javascript/commit/05059f2)
Returning the value from search responses when the value exists
=> fix(search): Add abTestID to search response

algolia/search/responses_search.go
| Related Issue     | None
The `hits` property in a search response (`QueryRes`) is now marshalled as `hits` instead of `Hits`.
The `hits` property in a search response (`QueryRes`) was marshalled as `Hits` instead of `hits`, which breaks an integration with InstantSearch in a back-end search implementation. The JS client requires `hits`.
=> fix(search) hits in search response are now marshalled as 'hits'

algolia/search/rule_consequence_params.go, algolia/search/rule_consequence_params_test.go
Implement the `UnmarshalJSON` on `AutomaticFacetFilter` to handle the case when `automaticFacetFilters` or `automaticOptionalFacetFilters` are just a `string`.
=> fix(search) handle automaticFacetFilters unmarshal from string

algolia/internal/opt/facet_filters_test.go, algolia/internal/opt/numeric_filters_test.go, algolia/internal/opt/optional_filters_test.go, algolia/internal/opt/tag_filters_test.go, algolia/opt/composable_filter.go, algolia/opt/composable_filter_test.go
One-string legacy filter deserialization behavior is fixed to handle parenthesis usage with multiple groups.
Added more tests to cover possible usages.
**PS:** This behavior is already fixed in other client libraries. This implementation is based on those PRs which are fixing the same issue.
https://github.com/algolia/algoliasearch-client-java-2/pull/771
https://github.com/algolia/algoliasearch-client-csharp/pull/803
When legacy one-string filters are used deserialization was not working as expected. 
Normally, it should work as below;
```
"color:green,color:yellow" => [["color:green"],["color:yellow"]] …
```
=> fix: handle composableFilterOption deserialization for legacy usage

algolia/search/rule_consequence_params.go, algolia/search/rule_consequence_params_test.go
Try first the legacy format parsing before new format and continue only if no edits are retrieved
Fix the unmarshalling of rules consequence using the legacy format to edit the query words. The permissive parsing of the new format was taking precedence leading to rules without edits.
=> fix: unmarshal the legacy format before trying the new one

.circleci/config.yml
Run ci with go 1.18, 1.19 and 1.20 but deprecate 1.13, 1.14 and 1.15.
Golang only supports the 2 latest versions so 1.18 is already unmaintained that's why I deprecated the oldest ones to keep the same amount of versions tested
=> chore: run ci with go 1.18, 1.19 and 1.20 but deprecate 1.13, 1.14 and 1.15

algolia/personalization/client_personalization.go, algolia/recommend/client_recommend.go, algolia/recommendation/client_personalization.go, algolia/search/account.go, algolia/search/client.go, algolia/search/client_dictionaries.go, algolia/search/index.go
Fix various miss or unpacked options parameter in `transport.Request` calls
Some options were silently ignored due to it
=> fix: pass unpacked options in some requests call

algolia/search/index.go, algolia/search/utils.go, algolia/search/utils_test.go
Support waiting tasks with a Recommend-level scope. It is slightly different than the index-level task because it expects a model name in the URL. Note that this is historical though, the model name is now useless and both index-level and recommend-level actually work similarly behind the hood.
Add the abillity to build recommend rules in Metis.
=> feat(recommend): implement Recommend-level waitTask

ChangeLog.md
Updated some comparison links in the changelog because they did not refer to existing tags.
Changelog comparison links were broken because they we pointing to inexistent tags.
=> docs(changelog): Fix broken comparison links

algolia/search/utils.go, algolia/search/utils_test.go
Treat taskIDs below 1000 as being of "index" scope.
An error was thrown when taskIDs were below 1000 instead of accepting it as being of "index" scope.
=> fix(recommend): Handle taskIDs below 1000 as index scope

algolia/search/client.go, algolia/search/client_interface.go, algolia/search/index.go, algolia/search/index_interface.go, algolia/search/utils.go, algolia/search/utils_test.go
Add a `WaitRecommendTask` function.
Fix `waitTask` implementation for Recommend: use a dedicated function rather than relying on the `taskID` value, which is computed differently in Metis.
=> fix(recommend): implement dedicated waitRecommendTask function

algolia/search/rendering_content.go, algolia/search/rendering_content_test.go
Parse the `redirect` attribute and prevent to serialize `FacetOrdering` when nil
When unmarshalling a rendering content with only `redirect`, the attribute was ignored. Then marshalling the struct resulted in an invalid renderint content because `FacetOrdering` set to nil is invalid
=> feat(renderingContent): parse the redirect attribute

algolia/transport/transport.go, algolia/transport/transport_test.go
Allow to override existing header with different case instead of appending values
The current behaviour append header values but the search engine doesn't support multivalued headers. It leads to undefined behaviour based on the header ordering.
=> fix(transport): allow to override existing header with different case

algolia/search/rule.go, algolia/search/rule_consequence.go, algolia/search/rule_test.go
Previously the SDK would silently drop fields specific to redirect-based rules.  This change adds the missing fields so that it is possible to fetch and re-submit rules without losing the redirect information.
Ideally the SDK would support this natively for all types, but that is a bigger job!
=> fix(rules): missing redirect field in RuleConsequence

release.sh
Fix the release script to be usable:
- Rake is missing to autofill the Changelog
- `git push --tags` was pushing all tags of the repo instead of the one created by the release
For now, the Changelog needs to be set manually, it could be improved in the futur
Tested during the release of v3.30.1: https://github.com/algolia/algoliasearch-client-go/commit/b7c4776fb36744172f4d75c4c5bfddafb412dccf
=> chore(release.sh): fix release script

algolia/insights/types.go, algolia/insights/types_test.go, algolia/insights/user_client.go, cts/insights/sending_events_test.go
| BC breaks?        | no
| Related Issue     | Fix #749 [CR-6348]
Add the optional subtype property to the Event struct for Insights
Users couldn't send an event subtype
[CR-6348]: https://algolia.atlassian.net/browse/CR-6348?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(insights): implement event optional subtype

algolia/search/responses_search.go
Porting this PR to v3 : https://github.com/algolia/api-clients-automation/pull/3688
Return the parameter `_automaticInsights` (when possible) when calling search.
I need this value in the Recommend mono-repository so that the Recommend API can forward this parameter to the Recommend client.
=> feat(specs): add (optional) _automaticInsights to search result

algolia/insights/types.go
Add missing props to the Insights event type
Some props are not strongly typed because they can be multiple things (usually string or number)
In the future, we should allow extracting data from the opts variadic param
fixes #767
=> fix(insights): add missing props
