algoliasearch/Client.go, algoliasearch/Client_test.go, algoliasearch/Index.go, algoliasearch/IndexIterator.go, algoliasearch/Transport.go
I have my vim configured to automatically run `gofmt` on every save so I wind up running gofmt and polluting my feature/fix branch. Instead let's just run gofmt once over everything so we can use it from here on in.
=> run gofmt on the src

algoliasearch/algoliasearch.go, algoliasearch/client.go, algoliasearch/client_test.go, algoliasearch/index.go, algoliasearch/index_iterator.go
This allows easier mocking of Algolia within application tests
=> Expose interfaces instead of struct types

algoliasearch/index.go
=> Encode GetObject attributes as JSON

algoliasearch/algoliasearch.go, algoliasearch/client.go
=> Add DeleteIndex and ClearIndex methods to the Client

algoliasearch/algoliasearch.go, algoliasearch/client_test.go, algoliasearch/index.go
=> Fix `Index.DeleteByQuery`

algoliasearch/types_browse.go
=> Add missing field (warning) to BrowseRes

algoliasearch/types_query.go
=> Add missing fields to QueryRes + Fix one field (params)

algoliasearch/transport.go
=> Return the raw response along the JSON error if Transport.handleResponse

algoliasearch/index.go
Issue https://github.com/algolia/algoliasearch-client-go/issues/63
=> Use the POST method for Browse

algoliasearch/client_test.go, algoliasearch/types_logs.go
Fix the `AnswerCode` type (from `int` to `string`) and add missing fields for the `LogRes` struct.
=> Fix LogRes type

.travis.yml, algoliasearch/client_test.go
=> Add test for Client.ListIndexes

algoliasearch/check_query.go
=> feat(Query): Handle facetingAfterDistinct parameter

algoliasearch/algoliasearch.go, algoliasearch/check_settings.go, algoliasearch/index.go, algoliasearch/index_test.go, algoliasearch/types_search_facet.go
=> Feat search facet

algoliasearch/index_test.go
=> test: Add type checking tests for inside{BoundingBox,Polygon}

algoliasearch/check_key.go, algoliasearch/secured_api_key.go, algoliasearch/secured_api_key_test.go
=> feat: Allow restrictSources parameter with secured API keys

ChangeLog, algoliasearch/algoliasearch.go, algoliasearch/client.go, algoliasearch/index.go
@aseure would love your feedback on this. I did not add test because in the end the old tests still work (it's a simple forwarding of the argument).
=> Create *APIKey alternatives to *UserKey functions

algoliasearch/types_key.go
fixes #403, lmk if something is wrong here. Didn't see an existing test to add to
=> Add Indexes to Key

algoliasearch/algoliasearch.go, algoliasearch/client.go, algoliasearch/client_test.go, algoliasearch/testing_test.go, algoliasearch/types_mcm.go
Introduce Multi Cluster Management 🎉 
Any feedback is very welcome since I'm fairly new to Go.
=> Introduce Multi Cluster Management (ie MCM)

algoliasearch/algoliasearch.go, algoliasearch/client.go, algoliasearch/client_test.go
Implement the new `Client.RestoreAPIKey` method.
=> added: implement Client.RestoreAPIKey

algolia/search/index_objects.go, algolia/search/responses_search.go, cts/index/search_test.go
=> Deprecate and replace unit testing relevance functions

ChangeLog.md
Fix a typo in changelog.
Better not to have.
=> docs(changelog): fix a typo

algolia/recommendation/client.go, algolia/recommendation/client_personalization.go, algolia/recommendation/configuration.go, algolia/recommendation/responses_personalization.go, algolia/recommendation/types_personalization.go, algolia/recommendation/utils.go, algolia/search/client_interface.go, algolia/search/client_personalization.go, algolia/search/personalization.go
=> Implement Recommendation client for Personalization features

algolia/search/responses_log.go, algolia/search/responses_log_test.go
Added fields:
- `Exhaustive` boolean
- `Index` string
- `InnerQueries` array (close #593)
=> Expose new fields in LogRes struct returned by GetLogs()

cts/recommendation/personalization_strategy_test.go, cts/testing_utils.go
=> test: add Recommendation test for Personalization strategy

README.md, cts/testing_utils.go
Update the README to add the CircleCI and change the env variable in the tests
=> chore(circleci): adds badge and change tests CI variable

algolia/internal/gen/options.go, algolia/search/settings.go, cts/index/settings_test.go
=> feat(search): accept enablePersonalization boolean as a valid setting parameter

algolia/search/rule_consequence.go
=> feat(rule): expose Rule.RuleConsequence.Promote.ObjectIDs string slice

algolia/search/rule.go, algolia/search/rule_test.go, cts/index/rule_test.go
=> feat(rule): implement multi-condition rules

algolia/analytics/responses_ab_testing.go
| New feature?      | no 
Use the correct type for the click significance.
=> fix(analytics): correct the click significance type

algolia/search/responses_search.go
| BC breaks?        | no
| Related Issue     |
Adds the definition of a new field on `QueryRes`: `Extensions`.
=> feat(QueryRes): add support for extensions field

algolia/query_suggestions/client.go, algolia/query_suggestions/client_config.go, algolia/query_suggestions/configuration.go, algolia/query_suggestions/utils.go, cts/query_suggestions/config_test.go, cts/testing_utils.go
| Related Issue     | #658 
Implemented Query Suggestions API client excepts `get configuration status` and `get a log file`.
https://www.algolia.com/doc/rest-api/query-suggestions/#quick-reference
=> Implement client for query suggestions API

algolia/search/index.go, algolia/search/index_test.go, algolia/suggestions/client.go, algolia/suggestions/client_config.go, algolia/suggestions/configuration.go, algolia/suggestions/utils.go, cts/search/mcm_test.go, cts/suggestions/config_test.go, cts/testing_utils.go
This PR fixes lint issues caused by previous commits
Lint CI step doesn't pass
=> chore: fix lint issues

algolia/search/rendering_content.go, algolia/search/rendering_content_test.go, algolia/search/responses_search.go, algolia/search/rule_consequence_params.go
This PR Introduces models for dynamic facet ordering support
=> feat(facet ordering): Dynamic facet ordering support

algolia/internal/gen/templates/settings.go.tmpl, algolia/search/extensions.go, algolia/search/extensions_test.go, algolia/search/settings.go
| BC breaks?        | no    
Add reranking extension structure to the index settings
=> feat(reranking extensions): Implement Reranking extensions settings

.circleci/config.yml, algolia/personalization/client.go, algolia/recommend/client.go, algolia/recommend/client_recommend.go, algolia/recommend/configuration.go, algolia/recommend/types_recommend.go, cts/recommend/recommend_test.go
Introduces [Recommend](https://www.algolia.com/doc/rest-api/recommend/#get-recommendations) client implementation
=> feat(recommend): implement Recommend client

algolia/search/utils.go
Update wait task logic to not wait for more than 10s between calls, down from 10m, and remove the randomness.
This realigns the go client with the other api clients and improves responsiveness.
=> feat: update wait task max wait time

algolia/search/rule.go, algolia/search/rule_test.go
Add the support of `tags` in the rules parsing
=> feat: add support of tags parsing in rules

release.sh
Fix the release script: the path to the transport file was outdated and the tag format was wrong
=> chore: fix release script
